### ISSUE TITLE
Get quotes for stripping skirting boards and door jams

### ISSUE THREAD

**Issue by clarecoatman** [liamwelton/house-ren#58]
https://www.fantastichandyman.co.uk/prices/
https://londonpaintstrippers.multiscreensite.com/services
https://www.freeindex.co.uk/profile(london-paint-strippers)_478848.htm

Layer of sanding sealant
Sand?
Wax

**Comment by liamwelton** [comment]
Going to merge this task into this one to make it easier to track: https://github.com/liamwelton/house-ren/issues/13
